export const ACTION_TYPES = {
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_START: "LOGIN_START",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    CHANGE_BOARD: "CHANGE_BOARD",
    CHANGE_X_IS_NEXT: "CHANGE_X_IS_NEXT",
    CHANGE_GAME_TYPE: "CHANGE_GAME_TYPE"
}